### model
model_name_or_path: $model_name_or_path
trust_remote_code: true

### method
finetuning_type: full

### dataset
task: $task  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: en
n_shot: $n_shot

### output
save_dir: $save_dir

### eval
batch_size: 4
